CREATE TABLE IF NOT EXISTS FILMS (
id_film INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar NOT NULL,
release_date date NOT NULL,
duration INTEGER,
id_mpa INTEGER
);

CREATE TABLE IF NOT EXISTS film_genres (
id_film integer,
id_genre integer
);

CREATE TABLE IF NOT EXISTS genres (
id_genre integer PRIMARY KEY,
name_genre varchar
);

ALTER TABLE FILM_GENRES ADD constraint fk_1 FOREIGN KEY (id_film) REFERENCES films;
ALTER TABLE FILM_GENRES ADD constraint fk_2 FOREIGN KEY (id_genre) REFERENCES genres;

CREATE TABLE IF NOT EXISTS mpa (
id_mpa integer PRIMARY KEY,
name_mpa varchar
);
ALTER TABLE films ADD constraint fk_3 FOREIGN KEY (id_mpa) REFERENCES mpa;

CREATE TABLE IF NOT EXISTS likes (
id_film integer,
id_user integer
);

CREATE TABLE IF NOT EXISTS users (
id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
email varchar,
login varchar,
birthday date
);

CREATE TABLE IF NOT EXISTS friends (
id_user integer REFERENCES users,
id_friend integer REFERENCES users
);

ALTER TABLE likes ADD constraint fk_4 FOREIGN KEY (id_film) REFERENCES films;
ALTER TABLE likes ADD constraint fk_5 FOREIGN KEY (id_user) REFERENCES users;
